//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanly.Models.framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class dangky
    {
        public int id_dangky { get; set; }
        public string tenkhachhang { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
        public string matkkhau { get; set; }
        public Nullable<int> sdt { get; set; }
    }
}
