//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanly.Models.framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.cart_details = new HashSet<cart_details>();
        }
    
        public int id_sanpham { get; set; }
        public string tensanpham { get; set; }
        public Nullable<int> giasp { get; set; }
        public Nullable<int> soluong { get; set; }
        public string hinhanh { get; set; }
        public string mota { get; set; }
        public Nullable<int> tinhtrang { get; set; }
        public Nullable<int> id_danhmuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_details> cart_details { get; set; }
        public virtual danhmuc danhmuc { get; set; }
    }
}
